### ISSUE TITLE
thanks for your code!

### ISSUE THREAD

**Issue by liuqi123123** [yzhaiustc/Optimizing-SGEMM-on-NVIDIA-Turing-GPUs#1]
your code is very helpful to understand the optimization of matrix multiplication on GPU! Thanks very much,
and are there more high-performance approaches which are better than kernel 11?

**Comment by yzhaiustc** [comment]
Thank you for the interest in this project.
To further improve the performance, the next step would be to down to the assembly level and seek squeezing more performance there. I would suggest you refer to https://github.com/NervanaSystems/maxas/wiki/SGEMM for ideas.
Since NVIDIA does not release its official assembler, one can only adopt third-party assemblers for development.
Kepler assembler: https://github.com/xiuxiazhang/KeplerAs
Maxwell assembler: https://github.com/NervanaSystems/maxas
Volta/Turing assembler: https://github.com/daadaada/turingas
Hope this helps. Good luck :)

**Comment by liuqi123123** [comment]
wow! so generous are you ! it will help me much! thanks!
